title: TECH Setu
email: techsetuu@gmail.com
year: 2023
description: >-
  A non-profit initiative working on bridging the technological gap
  among IT Industry, IT Students and IT Professionals.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://techsetu.org"
image_base_url: https://techsetu.sirv.com/img
# image_base_url: /assets/img
thumbnail: thumbnail.jpg

twitter_username: '@tech_setu'
google_analytics: G-6YGR4H8C5L

permalink: /blogs/:year/:month/:day/:title/

# Build settings
markdown: kramdown
