title: Developers Association of Nepal
email: devnepal2025@gmail.com
year: 2025
description: >-
  A non-profit organization working for building the skilled
  Software Developers workforce in Nepal
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://devnepal.org"
channel: https://t.me/dev_nepal
# asset_url: https://devnepal.sirv.com/img
asset_url: /assets/img
thumbnail: thumbnail.jpg

# twitter_username: '@tech_setu'
google_analytics:

permalink: /blogs/:year/:month/:day/:title/

# Build settings
markdown: kramdown
